spring:
  main:
    # No need to start a tomcat, so we can disable that
    web-application-type: none

  # You need to configure the client both for the cloud clientfactory and feign
  cloud.httpclientfactories:
    apache.enabled: true
    ok.enabled: false

feign:
  httpclient.enabled: true
  okhttp.enabled: false

logging:
  level:
    ROOT: INFO
    de.dev.eth0.springboot.httpclient: DEBUG
    org.apache.http: DEBUG

http:
  client:
    proxies:
      - hostPatterns: []
        host: localhost
        port: 3128

    timeouts:
      connectionTimeout: 5000
      socketTimeout: 10000

---

# Profile which enables OkHttp instead of Apache
spring:
  profiles: okhttp

  cloud.httpclientfactories:
    apache.enabled: false
    ok.enabled: true

feign:
  httpclient.enabled: false
  okhttp.enabled: true