spring:
  main:
    # No need to start a tomcat, so we can disable that
    web-application-type: none

  # You need to configure the client both for the cloud clientfactory and feign
  cloud.httpclientfactories:
    apache.enabled: true
    ok.enabled: false

feign:
  httpclient.enabled: true
  okhttp.enabled: false

logging:
  level:
    ROOT: INFO
    de.dev.eth0.springboot.httpclient: DEBUG
    org.apache.http: DEBUG

http:
  client:
    proxies:
      # Demo case for a request using a (optionally authenticated) proxy. Make sure, you have one running
      - hostPatterns: ["gturnquist-quoters.cfapps.io"]
        proxyHost: localhost
        proxyPort: 3129
        proxyUser: test
        proxyPassword: test123

    timeouts:
      connectionTimeout: 5000
      socketTimeout: 10000
    # Set desired SSL Context
    sslContext: TLSv1.2

# URL of hte used demo application
demoUrl: "https://gturnquist-quoters.cfapps.io/api/random"

---
# Profile which demonstrates a custom truststore
spring.profiles: truststore

http:
  client:
    truststore:
      path: classpath:truststore.jks
      password: changeit

demoUrl: "https://localhost:8443/random.json"
---


# Profile which enables OkHttp instead of Apache
spring:
  profiles: okhttp

  cloud.httpclientfactories:
    apache.enabled: false
    ok.enabled: true

feign:
  httpclient.enabled: false
  okhttp.enabled: true